p8105\_hw1\_jo2570
================
Jai Oberoi
17/09/2019

Run tidyverse package and create a data frame called
    hw1\_df

``` r
library(tidyverse)
```

    ## ── Attaching packages ──────────────────────────────────── tidyverse 1.2.1 ──

    ## ✔ ggplot2 3.2.1     ✔ purrr   0.3.2
    ## ✔ tibble  2.1.3     ✔ dplyr   0.8.3
    ## ✔ tidyr   0.8.3     ✔ stringr 1.4.0
    ## ✔ readr   1.3.1     ✔ forcats 0.4.0

    ## ── Conflicts ─────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

``` r
hw1_df = tibble( 
  samp = rnorm(8),
  vec_logical = samp > 0,
  vec_char = c("a", "b", "c", "d", "e", "f", "g", "h"),
  vec_factor = factor(c("newyork", "boston", "atlanta", "newyork", "boston", "atlanta", "newyork", "boston"))
)


#attempting to take the mean od each variable in data frame hw1_df 

#mean of the random normal sample, samp: 
mean(pull(hw1_df, samp))
```

    ## [1] -0.6878247

``` r
#we can get a mean value for the variable samp  

#mean of the variable vec_logical
mean(pull(hw1_df, vec_logical))  
```

    ## [1] 0.25

``` r
#we can get a mean value for vec_logical 
    
#mean of the variable vec_logical
mean(pull(hw1_df, vec_char))  
```

    ## Warning in mean.default(pull(hw1_df, vec_char)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

``` r
#we cannot take the mean of vec_char - we get an error saying that the argument is not numeric or logical 

#mean of the variable vec_factor
mean(pull(hw1_df, vec_factor)) 
```

    ## Warning in mean.default(pull(hw1_df, vec_factor)): argument is not numeric
    ## or logical: returning NA

    ## [1] NA

``` r
#we cannot take the mean of vec_factor - we get an error saying that the argument is not numeric or logical 
```
